blueprint:
  name: Room Occupancy Using Multiple Sensors
  description: This blueprint uses multiple sensors to detect room occupancy.
  source_url: https://github.com/BoasHoeven/home_assistant_blueprints/blob/main/blueprints/advanced_room_occupancy_detection.yaml
  domain: automation
  input:
    motion_entities:
      name: Motion Sensors
      description: Motion sensor entities that will be used for detecting presence in the room.
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true
    presence_entity:
      name: Presence sensor used to detect if someone is inside the room
      description: Presence sensor entity that will be used for detecting presence in the room.
      default: ''
      selector:
        entity:
          domain: binary_sensor
          device_class: presence
    bathroom_presence_entity:
      name: Bathroom Presence Sensor
      description: The bathroom presence sensor entity responsible for monitoring presence events.
      default: ''
      selector:
        entity:
          domain: sensor
    light_entities:
      name: Light
      selector:
        target:
          entity:
            domain: light
    brightness_percentage:
      name: Brightness percentage
      description: Brightness level in percentage for the light to turn on.
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: '%'
    turn_on_transition_duration:
      name: Turn on transition duration
      description: Time in seconds for the light to turn on gradually.
      default: 1
      selector:
        number:
          min: 0
          max: 3
          unit_of_measurement: seconds
    turn_off_transition_duration:
      name: Turn off transition duration
      description: Time in seconds for the light to turn off gradually.
      default: 10
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds

variables:
  var_presence_entity: !input presence_entity
  var_bathroom_presence_entity: !input bathroom_presence_entity

mode: queued
max: 25
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entities
    to:
      - 'on'
      - 'off'
  - platform: state
    entity_id: !input presence_entity
    to:
      - 'on'
      - 'off'
  - platform: state
    entity_id: !input bathroom_presence_entity
    attribute: presence_event
    to:
      - 'leave'
      - 'approach'

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' or (trigger.entity_id == var_bathroom_presence_entity and trigger.to_state.attributes.presence_event == 'approach') }}"
        sequence:
          - service: light.turn_on
            target: !input light_entities
            data:
              brightness_pct: !input brightness_percentage
              transition: !input turn_on_transition_duration
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' or (trigger.entity_id == var_bathroom_presence_entity and trigger.to_state.attributes.presence_event == 'leave') }}"
        sequence:
          - condition: state
            entity_id: !input presence_entity
            state: 'off'
          - service: light.turn_off
            target: !input light_entities
            data:
              transition: !input turn_off_transition_duration

